---
- block:
    - name: Get instance config
      set_fact:
        instance_conf: "{{ lookup('file', molecule_instance_config) | molecule_from_yaml }}"
  rescue:
    - name: Set an empty instance config if file is missing
      set_fact:
        instance_conf: {}

- name: Send termination command to instance(s)
  ec2:
    instance_ids: "{{ item }}"
    region: "{{ mec2_aws_region }}"
    state: absent
  loop: "{{ instance_conf | map(attribute='instance_ids') | list | flatten }}"
  register: mec2_destroy_instances
  async: 7200
  poll: 0
  when: instance_conf != {}

- name: Wait for instance(s) deletion to complete
  async_status:
    jid: "{{ item.ansible_job_id }}"
  loop: "{{ mec2_destroy_instances.results }}"
  register: mec2_ec2_jobs
  until: mec2_ec2_jobs.finished
  retries: 300
  when: instance_conf != {}

- name: Delete remote keypair
  ec2_key:
    name: "{{ mec2_keypair_name }}"
    state: absent

# NOTE: mandatory configuration for Molecule to function!
- name: Populate instance config
  set_fact:
    instance_conf: {}

- name: Dump instance config
  copy:
    content: "{{ instance_conf | to_json | from_json | molecule_to_yaml | molecule_header }}"
    dest: "{{ molecule_instance_config }}"
