---
- block:
    - name: Get instance config
      set_fact:
        instance_conf: "{{ lookup('file', molecule_instance_config) | molecule_from_yaml }}"
  rescue:
    - name: Set an empty instance config if file is missing
      set_fact:
        instance_conf: {}

- name: Get current instance IDs
  set_fact:
    mec2_instances: "{{ instance_conf | map(attribute='instance_ids') | list | flatten }}"

- name: Send termination command to instance(s)
  ec2:
    instance_ids: "{{ mec2_instances }}"
    region: "{{ mec2_aws_region }}"
    state: absent
  async: 7200
  poll: 0
  when: instance_conf != {}

- name: Wait for instance(s) deletion to complete
  ec2_instance_facts:
    instance_ids: "{{ mec2_instances }}"
  register: mec2_ec2_instance_facts
  until: >
    (mec2_ec2_instance_facts.instances | map(attribute='state.name') | list | unique) == ['terminated']
  retries: 60
  delay: 10
  when: instance_conf != {}

- name: Delete remote keypair
  ec2_key:
    name: "{{ mec2_keypair_name }}"
    state: absent

# NOTE: mandatory configuration for Molecule to function!
- name: Populate instance config
  set_fact:
    instance_conf: {}

- name: Dump instance config
  copy:
    content: "{{ instance_conf | to_json | from_json | molecule_to_yaml | molecule_header }}"
    dest: "{{ molecule_instance_config }}"
