---
- name: Ensure keypair local dir directory exists
  file:
    path: "{{ mec2_keypair_local_path | dirname }}"
    state: directory

- name: Create remote keypair
  ec2_key:
    name: "{{ mec2_keypair_name }}"
  register: mec2_new_keypair

- name: Persist the keypair private key
  copy:
    content: "{{ mec2_new_keypair.key.private_key }}"
    dest: "{{ mec2_keypair_local_path }}"
    mode: 0600
  when: mec2_new_keypair.changed
