---
- name: Ensure required variables are valid
  assert:
    that:
      - molecule_yml is defined
      - molecule_instance_config is defined
      - mec2_action in ['prepare', 'create', 'destroy']

- name: Get Molecule run UUID
  set_fact:
    mec2_molecule_state: "{{ lookup('file', lookup('env', 'MOLECULE_STATE_FILE')) | molecule_from_yaml }}"

- name: Set Molecule run UUID
  set_fact:
    mec2_molecule_run_uuid: "{{ mec2_molecule_state.run_uuid }}"

- name: Set keypair configuration variables
  set_fact:
    mec2_keypair_name: "{{ mec2_keypair_name_prefix + '-' + mec2_molecule_run_uuid }}"
    mec2_keypair_local_path: "{{ mec2_local_temp_dir }}/{{ mec2_molecule_run_uuid }}/ssh_key"

- name: Include distro configuration
  include_vars: distros.yml

- name: Include selected action tasks
  include_tasks: "{{ mec2_action }}.yml"
