---
- name: Ensure required variables are valid
  assert:
    that:
      - molecule_yml is defined
      - molecule_instance_config is defined
      - mec2_action in ['prepare', 'create', 'destroy']

- name: Set run ID
  set_fact:
    mec2_molecule_run_id: "{{
      (lookup('file', lookup('env', 'MOLECULE_STATE_FILE')) | molecule_from_yaml)['run_uuid']
      | replace('-', '')
    }}"

- name: Setup role global variables
  set_fact:
    mec2_keypair_name: "{{ mec2_keypair_name_prefix + '-' + mec2_molecule_run_id }}"
    mec2_keypair_local_path: "{{ mec2_local_temp_dir }}/{{ mec2_molecule_run_id }}/ssh_key"
    mec2_security_group_name: "{{ mec2_security_group_name_prefix + '-' + mec2_molecule_run_id }}"
    mec2_security_group_rules: "{{ mec2_security_group_default_rules + mec2_security_group_extra_rules }}"

- name: Include distro configuration
  include_vars: distros.yml

- name: Include selected action tasks
  include_tasks: "{{ mec2_action }}.yml"
